version: '3.2'

services:
    soyboard:
        restart: always
        build: .
        image: soyboard
        volumes: ['.:/app']
        env_file:
            - .env-file
        expose:
            - "80"
